"""Provider-neutral target planning for Contract4Agents."""

from contract4agents.planning._errors import PlanningError, PlanningIssue
from contract4agents.planning._locators import (
    LocatorDescription,
    LocatorFamily,
    describe_locator,
)
from contract4agents.planning._models import (
    PLAN_VERSION,
    AdapterMappingResolver,
    AdapterPlan,
    AgentPlan,
    BindingExecution,
    BindingKind,
    BindingPlan,
    BindingResolution,
    CompositionMappingPlan,
    ControlMappingPlan,
    GrantMappingPlan,
    HostObligationPlan,
    IsolationDimension,
    IsolationDimensionPlan,
    IsolationMappingPlan,
    MappingOutcome,
    MappingSupport,
    MaterializationPlan,
    OperationalControlMappingPlan,
    PlannerCapabilities,
    in_process_isolation_support,
)
from contract4agents.planning._planner import plan_materialization
from contract4agents.planning._serialization import (
    PlanJsonValue,
    canonical_materialization_plan_json,
    compute_plan_digest,
    materialization_plan_data,
)

__all__ = [
    "PLAN_VERSION",
    "AdapterMappingResolver",
    "AdapterPlan",
    "AgentPlan",
    "BindingExecution",
    "BindingKind",
    "BindingPlan",
    "BindingResolution",
    "CompositionMappingPlan",
    "ControlMappingPlan",
    "OperationalControlMappingPlan",
    "GrantMappingPlan",
    "HostObligationPlan",
    "IsolationDimension",
    "IsolationDimensionPlan",
    "IsolationMappingPlan",
    "LocatorDescription",
    "LocatorFamily",
    "MappingOutcome",
    "MappingSupport",
    "MaterializationPlan",
    "PlanJsonValue",
    "PlannerCapabilities",
    "PlanningError",
    "PlanningIssue",
    "canonical_materialization_plan_json",
    "compute_plan_digest",
    "describe_locator",
    "in_process_isolation_support",
    "materialization_plan_data",
    "plan_materialization",
]
